---
title: "Day 1: Grammar of Graphics"
author: "Aaron R. Williams"
output:
  html_document:
    code_folding: hide
    toc: TRUE
    toc_float: TRUE
    css: !expr here::here("www", "web_report.css")
    editor_options:
      chunk_output_type: console
---

```{r}
library(tidyverse)

```

## Exercise 1

```{r}
# scatter plot of pressures and wind speeds
ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind))

storms %>%
  ggplot() +
  geom_point(mapping = aes(x = pressure, y = wind))

```

## Exercise 2

```{r}
ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind, color = category))

ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind, color = "green"))

ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind), color = "green")

ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind), alpha = 0.2)

```

## Exercise 3

```{r}
options(scipen = 999)

ggplot(data = msleep) +
  geom_point(mapping = aes(x = bodywt, y = sleep_total)) +
  scale_x_log10() +
  scale_y_continuous(limits = c(0, NA))

```

## Exercise 4

```{r}
data <- tibble(x = 1:10, y = 1:10)

ggplot(data = data) +
  geom_blank(mapping = aes(x = x, y = y)) +
  coord_polar() +
  labs(title = "Polar coordinate system") +
  theme(plot.title = element_text(hjust = 0.5))

```

## Exercise 5

```{r}
ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind)) +
  facet_wrap(~ category)

```

## Exercise 6

```{r}
ggplot(data = storms) +
  geom_bar(mapping = aes(x = category))

storms %>%
  count(category) %>%
  ggplot() +
  geom_col(mapping = aes(x = category, y = n)) +
  labs(y = "count")

```

## Exercise 7

```{r}
ggplot(data = storms) +
  geom_bar(mapping = aes(x = category)) +
  labs(title = "Plot title") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

```

## Exercise 8

```{r}
# YOUR WORK GOES HERE

```

## Exercise 9

```{r}
storms_summary <- storms %>%  
  filter(category > 0) %>%
  distinct(name, year) %>%
  count(year)

ggplot(data = storms_summary) + 
  geom_line(mapping = aes(x = year, y = n)) +
  geom_point(mapping = aes(x = year, y = n))

```

## Exercise 10

```{r}
ggplot(data = storms, mapping = aes(x = pressure, y = wind)) +
  geom_point() + 
  geom_smooth()

ggplot(data = storms) +
  geom_point(mapping = aes(x = pressure, y = wind)) + 
  geom_smooth(mapping = aes(x = pressure, y = wind))


```

## Exercise 11

```{r}
ggplot(data = storms, mapping = aes(x = pressure, y = wind)) +
  geom_point() + 
  geom_smooth()

ggsave(filename = "favorite-plot.pdf", width = 6, height = 4)

```



